version: '3.8'

services:
  app:
    build: .
    container_name: clinici_md_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
    restart: always
    volumes:
      - ./img:/app/img
      - ./public:/app/public