-- Add new clinic features for filtering
ALTER TABLE clinics ADD COLUMN pediatric_dentistry BOOLEAN DEFAULT FALSE;
ALTER TABLE clinics ADD COLUMN parking BOOLEAN DEFAULT FALSE;
ALTER TABLE clinics ADD COLUMN sos BOOLEAN DEFAULT FALSE;
ALTER TABLE clinics ADD COLUMN work_24h BOOLEAN DEFAULT FALSE;
ALTER TABLE clinics ADD COLUMN credit BOOLEAN DEFAULT FALSE;
