-- Add SEO fields to clinics table
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS seo_keywords TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS seo_h1 TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS og_title TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS og_description TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS og_image TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS seo_canonical TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS seo_robots VARCHAR(50) DEFAULT 'index,follow';
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS seo_priority DECIMAL(2,1) DEFAULT 0.5;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS seo_schema_type VARCHAR(50) DEFAULT 'Dentist';
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS seo_schema_data JSONB;
